

/* Create Tables */

CREATE TABLE FOLLOWS
(
	ID VARCHAR(20) NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'アイディー',
	FOLLOWING_USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'アイディー',
	FOLLOWED_USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'アイディー',
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'フォロー関係を管理する';


CREATE TABLE TWEETS
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	CONTENT VARCHAR(280) NOT NULL COMMENT 'ツイートの内容',
	LOCATION VARCHAR(100) COMMENT 'ツイートした位置情報',
	DEVICE VARCHAR(30),
	REPLIED_COUNT INT UNSIGNED NOT NULL,
	RETWEETED_COUNT INT UNSIGNED NOT NULL,
	LIKED_COUNT INT UNSIGNED NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ツイートのテーブル';


-- this is sample table.
CREATE TABLE USERS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE COMMENT 'アイディー',
	DISPLAY_ID VARCHAR(30) NOT NULL,
	ENCRIPTED_PASSWORD CHAR(20) NOT NULL COMMENT 'パスワード',
	EMAIL VARCHAR(30) NOT NULL,
	PHONE_NUMBER VARCHAR(12),
	NAME VARCHAR(20),
	DESCRIPTION TEXT,
	LOCATION VARCHAR(100),
	WEBSITE_URL VARCHAR(100),
	BIRTHDAY DATE,
	IMAGE_URL VARCHAR(100),
	SIGN_IN_AT DATE NOT NULL,
	PRIVATE BOOLEAN NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ユーザ用 : this is sample table.';


CREATE TABLE USER_TWEET
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'アイディー',
	TWEET_ID BIGINT NOT NULL UNIQUE,
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '関連テーブル';



/* Create Foreign Keys */

ALTER TABLE USER_TWEET
	ADD CONSTRAINT FK_USER_TWEET_TWEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FOLLOWS
	ADD CONSTRAINT FK_FOLLOWS_USERS FOREIGN KEY (FOLLOWING_USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FOLLOWS
	ADD CONSTRAINT FK_FOLLOWS_USERS_ FOREIGN KEY (FOLLOWED_USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_TWEET
	ADD CONSTRAINT FK_USER_TWEET_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



