

/* Create Tables */

-- アカウントを管理するテーブル
CREATE TABLE ACCOUNTS
(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'アカウントID : アカウントのid',
	NAME VARCHAR(30) NOT NULL COMMENT 'アカウント名 : アカウント名',
	DISPLAY_ID VARCHAR(255) NOT NULL COMMENT 'ディスプレイID : @の後に続くアカウントのid
検索等に使われる',
	WEB_SITE_URL TEXT COMMENT 'ウェブサイトURL : ウロフィールに載せるwebのurl',
	DESCRIPTION TEXT COMMENT 'プロフィール文 : プロフィールに載せる文章',
	ICON_PATH TEXT NOT NULL COMMENT 'アイコンURL : ユーザのアイコンのパス',
	CREATED_AT DATETIME NOT NULL COMMENT '作成された時間',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新された時間',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'アカウントテーブル : アカウントを管理するテーブル';


-- ツイートを管理するテーブル
CREATE TABLE TWEETS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	BODY TEXT NOT NULL COMMENT ' : ツイートの文章',
	DEVICE_TYPE INT UNSIGNED NOT NULL COMMENT ' : ツイートしたデバイスのタイプ',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'TWIEETS : ツイートを管理するテーブル';


-- ツイートに対して投稿された画像のパスを紐づけるテーブル
-- seqでシーケンス番号(順番)を管理している
CREATE TABLE TWEET_IMAGES
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	TWEET_ID BIGINT UNSIGNED NOT NULL COMMENT ' : 画像が紐づくツイートのid',
	IMAGE_PATH TEXT NOT NULL COMMENT ' : ツイートに紐づく画像のurl',
	SEQ INT NOT NULL COMMENT ' : ツイートに載せる画像の順番',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'TWEET_IMAGES : ツイートに対して投稿された画像のパスを紐づけるテーブル
seqでシーケンス番号(順番)を管理している';


-- ユーザがどのツイートにいいねしたかを管理するテーブル
CREATE TABLE TWEET_LIKES
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	TWEET_ID BIGINT UNSIGNED NOT NULL COMMENT ' : いいねされたツイートのid',
	LIKED_USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'ユーザID : ツイートにいいねしたユーザのid',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'NEW_TABLE : ユーザがどのツイートにいいねしたかを管理するテーブル';


-- ユーザがどのツイート・リツイート・リプに対して返信をしたか管理するテーブル
-- typeとreply_parent_idで返信先が決まる
-- reply_parent_idのdescに例がある
CREATE TABLE TWEET_REPLIES
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	REPLY_USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'ユーザID : ツイートに返信したユーザのid',
	SEQ INT UNSIGNED NOT NULL COMMENT ' : 返信の順番',
	REPLY_PARENT_ID INT UNSIGNED NOT NULL COMMENT ' : 返信したツイートのid
typeと連動している
例 : 
type : 1、reply_parent_id  : 1
tweet_id 1のスレッドに対して返信

type : 2、reply_parent_id  : 1
retweet_id 1 のスレッドに対しての返信

type : 3、reply_parent_id  : 1
replies_id 1にたいしての返信
返信に対しての返信',
	TYPE INT UNSIGNED NOT NULL COMMENT ' : 返信したスレッドのタイプ
1 → tweet thread
2 → retweet thread
3 → reply thread',
	CREATED_AT DATETIME NOT NULL,
	UPDATED_AT DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'TWEET_REPLIES : ユーザがどのツイート・リツイート・リプに対して返信をしたか管理するテーブル
typeとreply_parent_idで返信先が決まる
reply_parent_idのdescに例がある';


-- ユーザを管理するテーブル
CREATE TABLE USERS
(
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ユーザID : ユーザのid
',
	EMAIL VARCHAR(255) NOT NULL COMMENT 'メールアドレス : ユーザのメールアドレス',
	PASSWORD TEXT NOT NULL COMMENT 'パスワード : ユーザのパスワード',
	TOKEN TEXT NOT NULL COMMENT 'トークン : ユーザのトークン',
	CREATED_AT DATETIME NOT NULL COMMENT '作成された時間',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新された時間',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ユーザテーブル : ユーザを管理するテーブル';


-- ユーザとアカウントの関連テーブル
CREATE TABLE USER_ACCOUNTS
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'アカウントID : アカウントのid
',
	USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'ユーザID : アカウントを所有しているユーザのid',
	ACCOUNT_ID BIGINT UNSIGNED NOT NULL COMMENT '所持アカウントID : ユーザの所有しているアカウントid',
	UPDATE_AT DATETIME NOT NULL COMMENT '更新された時間',
	CREATE_AT DATETIME NOT NULL COMMENT '作成された時間',
	SIGNED_IN_AT DATETIME NOT NULL COMMENT '直前サインイン時間 : アカウントのログインした時間',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ユーザとアカウント関連テーブル : ユーザとアカウントの関連テーブル';


-- フォローフォロワー関係を管理するテーブル
CREATE TABLE USER_FOLLOWS
(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'フォローフォロワー関係のID',
	USER_ID BIGINT UNSIGNED NOT NULL COMMENT '被フォローユーザID : フォローしたユーザのID',
	FOLLOWING_USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'フォローユーザID : フォローされたユーザのid',
	CREATED_AT DATETIME NOT NULL COMMENT '作成された時間',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新された時間',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'フォロー関係テーブル : フォローフォロワー関係を管理するテーブル';


-- ユーザがどのツイートに対してリツイートをしたのかを管理するテーブル
CREATE TABLE USER_RETWEETS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT COMMENT ' : ユーザのid
',
	USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'ユーザID : リツイートしたユーザのid',
	TWEET_ID BIGINT UNSIGNED NOT NULL COMMENT ' : リツイートしたtweet_id',
	BODY TEXT COMMENT ' : リツイートする際の文章',
	CREATED_AT DATETIME NOT NULL COMMENT '作成日',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'USER_RETWEETS : ユーザがどのツイートに対してリツイートをしたのかを管理するテーブル';


-- どのユーザがどのツイートをしたのかを管理するテーブル
-- USERとTWEETSの中間テーブル
CREATE TABLE USER_TWEETS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'ユーザID : ツイートしたユーザのid',
	TWEET_ID BIGINT UNSIGNED NOT NULL COMMENT ' : ユーザがツイートした時のid',
	UPDATED_AT DATETIME NOT NULL,
	CREATED_AT DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'USER_TWEETS : どのユーザがどのツイートをしたのかを管理するテーブル
USERとTWEETSの中間テーブル';



/* Create Indexes */

CREATE UNIQUE INDEX UQ_ACCOUNTS_ID USING BTREE ON ACCOUNTS (ID ASC);
CREATE UNIQUE INDEX UQ_ACCOUNTS_DISPLAY_ID USING BTREE ON ACCOUNTS (DISPLAY_ID ASC);
CREATE INDEX UQ_TWEET_IMAGES_TWEET_ID_IMAGE_PATH ON TWEET_IMAGES (TWEET_ID ASC, IMAGE_PATH ASC);
CREATE UNIQUE INDEX UQ_TWEET_LIKES_TWEET_ID_LIKED_USER_ID ON TWEET_LIKES (TWEET_ID ASC, LIKED_USER_ID ASC);
CREATE UNIQUE INDEX UQ_USERS_TOKEN ON USERS (TOKEN ASC);
CREATE UNIQUE INDEX UQ_USER_ACCOUNTS_ID USING BTREE ON USER_ACCOUNTS (ID ASC);
CREATE UNIQUE INDEX UQ_USER_FOLLOWS_XXX USING BTREE ON USER_FOLLOWS (ID ASC);
CREATE UNIQUE INDEX UQ_USER_RETWEET_USER_ID_RETWEET_ID ON USER_RETWEETS (USER_ID ASC, TWEET_ID ASC);
CREATE UNIQUE INDEX UQ_USER_TWEETS_USER_ID_TWEET_ID ON USER_TWEETS (USER_ID ASC, TWEET_ID ASC);



/* Create Foreign Keys */

ALTER TABLE USER_ACCOUNTS
	ADD CONSTRAINT FK_USER_ACCOUNTS_ACCOUNTS FOREIGN KEY (ACCOUNT_ID)
	REFERENCES ACCOUNTS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_IMAGES
	ADD CONSTRAINT FK_TWEET_IMAGES_TWIEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_LIKES
	ADD CONSTRAINT FK_TWEET_LIKES_TWIEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_RETWEETS
	ADD CONSTRAINT FK_USER_RETWEET_TWIEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_TWEETS
	ADD CONSTRAINT FK_USER_TWEETS_TWIEETS FOREIGN KEY (TWEET_ID)
	REFERENCES TWEETS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_LIKES
	ADD CONSTRAINT FK_TWEET_LIKES_USERS FOREIGN KEY (LIKED_USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_REPLIES
	ADD CONSTRAINT FK_TWEET_REPLIES_USERS FOREIGN KEY (REPLY_USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_ACCOUNTS
	ADD CONSTRAINT FK_USER_ACCOUNTS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_FOLLOWS
	ADD CONSTRAINT FK_USER_FOLLOWS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_FOLLOWS
	ADD CONSTRAINT FK_USER_FOLLOWS_USERS_FOLLOWING FOREIGN KEY (FOLLOWING_USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_RETWEETS
	ADD CONSTRAINT FK_USER_RETWEET_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_TWEETS
	ADD CONSTRAINT FK_USER_TWEETS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



